let titleBtn = require('titleBtn')
let titleInput = document.getElementById("titleInput")
let genreBtn = require('genreBtn')
let genreInput = document.getElementById("genreInput")
let descBtn = require('descBtn')
let descInput = document.getElementById("descInput")
let imgBtn = require('imgBtn')
let imgInput = document.getElementById("imgInput")
